### ISSUE TITLE
Clone Repository URL dialog enhancements

### ISSUE THREAD

**Issue by mhowes82** [oxygenxml/oxygen-git-plugin#105]
Love the plugin! Two suggestions for improving the Clone Repository dialog

- Change the Repository URL field to a pulldown menu with a history of URLs. When checking out an existing branch, not checked out previously using the plugin, it would be more convenient than having to always find/copy the URL and paste it into the dialog. Should default to the last-selected URL.
- Change the Destination Path field to default to the last-selected local repo folder. I use a single repo for all files, but, when adding an existing branch, I have to always select the local repo folder.

![image](https://user-images.githubusercontent.com/44412025/90828772-8f35c580-e30c-11ea-9729-a9de91b76016.png)

Thanks!

**Comment by sorincarbunaru** [comment]
Hello,

Please note that when you use this action you actually create a new clone/a new local repository. This means we will have a local working copy for each "Checkout branch". This "Checkout branch" is actually the initial one. Later you would need to checkout other branches inside the same working copy. This is not yet possible, but we are currently working on it.

Having the last paragraph in mind, I would say the following:
- making the first text field a drop-down list might or might not be very helpful, because you would normally not clone the same remote repository more than 1 time. Instead you would probably checkout different branches inside the same local clone.
- trying to clone inside the same folder twice should not be possible. At least I can't do it, and I expected this. I actually get this error:
![image](https://user-images.githubusercontent.com/10512384/91025746-76762a00-e602-11ea-9d7b-4a603eb7a247.png)

**Comment by sorincarbunaru** [comment]
Based on the previous comment, I think I can close this issue. Feel free to reopen if needed.

**Comment by mhowes82** [comment]
Thanks for the reply! Yes, I would like to see the ability to check more than one branch inside the repo and look forward to that feature.
