### ISSUE TITLE
Authentication for remote cannot be canceled on startup of Oxygen

### ISSUE THREAD

**Issue by JanVanderschoot** [oxygenxml/Oxygen-Git-Plugin#32]
The situation is now that I can only do regular work in Oxygen after providing the user name and password for a remote on Gitlab. I would understand that after canceling the authentication there is no push or pull available.

**Comment by BeniaminSavu** [comment]
Hi,

Thank you for feedback. It was indeed a bug with the authentication dialog, the problem was that at some point after you cancel it, the push, pull and other actions buttons would be unavailable , but I think it is fixed now and it will be available in the next release. 

So I want to know if it is the same bug. If you can please give me some more details that would be great. When does the authentication dialog appear ? The push and pull are not available after you cancel the authentication dialog ?

**Comment by JanVanderschoot** [comment]
Hi,

When I launch Oxygen, I am presented with a dialog “Authorization required – refs”. If I press the Cancel button, the same modal dialog reappears. Only after I fill out the correct User/Password the will the dialog disappear.

I think I should be able to Cancel the authentication (and start working in Oxygen). The logical consequence should (rather *must*) be that I will not able to push to or pull from the remote repositories. However, it is not logical that I need to authenticate with Gitlab in order to be able to work on local files (living in a local working repo or outside of it).

The situation you describe below (unaivalable buttons) is not a problem in my view, but correct behaviour. Without authentication you should not be able to access the remote repositories.

Kind regards,

Jan Vanderschoot

**Comment by BeniaminSavu** [comment]
We saw the problem and it should be fixed now. The dialog should not appear anymore when you start Oxygen. For an unknown reason I was unable to reproduce this situation with the dialog appearing on startup of Oxygen, so if you can, please let us know if the problem still persists.

**Comment by JanVanderschoot** [comment]
Hi, the problem is gone. Thanks!
