### ISSUE TITLE
Support for git tag

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-git-plugin#49]
As asked here:
https://www.oxygenxml.com/forum/post44586.html#p44586

**Comment by kirkilj** [comment]
+1: This feature would take us one step closer to being able to use our workflow without having to have a terminal window open at all times.

**Comment by AlexJitianu** [comment]
Code review:

 1. TagsDialog ar fi bine sa extinda OKCancelDialog ca sa beneficieze de diverse fixuri. De exemplu cand dai ESC sa se inchida dialogul
1.TagsDialog.columnWidthPer este o constanta. Sa folosim majuscule.
1.TagsDialog.createDeleteListener() - m-as astepta ca acea stergere sa se faca intern, intr-o metoda din TagsTableModel. Un remove(int). De asemenea, fireTableStructureChanged este cam mult. M-as astepta sa facem un fireTableRowsDeleted. Si sa scoatem acel tagsTable.repaint();. Daca se emit notificarile corecte tabela se se reface singura.
1.Tot in TagsDialog, afisarea dialogului cu detalii sa o facem pe mouseClicked

**Comment by AlexJitianu** [comment]
1. `CreateTagAction` 
1.1. Let's put static fields first. There's a `logger` after other fields
2. Proper document the constructor parameter
3. `CreateTagDialog`
3.1.  there's no point in having a parameter for the title on the constructor. It can use internally the correct tag.
3.2. redundant instantiation of pushTagCheckBox
3.3. the call `updateUI(tagTitleField.getText());`. There is no text yet. it's a bit misleading. I would just pass an empty string.
3.4. that `KeyListener` on which we call `updateUI`. If I type a 20 characters tag name, this `updateUI` is called 20 times. Let's implement a coalescing. have a look at `com.oxygenxml.git.view.CoalescedEventUpdater` and how it is used. Let's take one step further and create a `CoalescingDocumentListener(Runnable)` to simplify the installment of such a support. 
4. `TagsDialog` - let's not hijack the `Cancel` and delete the tag. What happens now is that when you press ESC it actually deletes the tag instead of closing the dialog. I suggest having something like in the picture below. Actions with icons under the table for `Push` and `Delete` and just a `Close` button under that closes the dialog
![image](https://user-images.githubusercontent.com/7802649/132672382-0d4ff593-1739-4e6b-afb4-22417a521cc1.png)

**Comment by kirkilj** [comment]
It's exciting to see support for Git tags coming. As I might have described previously, we use them to version submodules so that a parent doc repo will know which version of a software component's documentation should be used with the current branch of the parent repo. This was the driver for one of my past suggestions, which was to let the writer know if a newer tag was created on a submodule's repo than the one current in use so they can decide whether they should use the newer one instead of the current one.

Will a submodule's tag be visible in the staging view?

Are you planning to show tags as well as branches in the branch manager view?

Will the history view show the tag name if one exists for a commit?

Let me know if you're looking for testers for tag support.

**Comment by sorincarbunaru** [comment]
Hi John,

The Tags support is still work-in-progress, but we will have to finish soon, because we want to release the Git Client add-on in 2-3 weeks or so. This means that, although we expect our implementation of the feature to be enough for many of our users, perhaps it won't be a perfect fit for everybody. But, of course, we will refine this feature in future versions.

Now, to answer your questions (although in a different order :D):
- The tags will be presented in a dialog box. This dialog box will be shown when using a toolbar action in Git Staging.
- The Git History view is already capable of presenting tags created using other Git clients, and it will definitely show the tags created using our client.
- We are working as we speak on properly presenting the tags for submodules (the submodule will need to be opened in Git Staging for this to work).

Knowing that you would be interested in testing the new features, we have already thought about sending you a Git Client kit a few weeks before the public release. Hopefully the Tags feature will be almost completed by next week so that my colleagues can send you a kit.

Keep in touch!

**Comment by GabrielNedianu** [comment]
Code review was implemented.

> 1. `CreateTagAction`
>    1.1. Let's put static fields first. There's a `logger` after other fields
> 2. Proper document the constructor parameter
> 3. `CreateTagDialog`
>    3.1.  there's no point in having a parameter for the title on the constructor. It can use internally the correct tag.
>    3.2. redundant instantiation of pushTagCheckBox
>    3.3. the call `updateUI(tagTitleField.getText());`. There is no text yet. it's a bit misleading. I would just pass an empty string.
>    3.4. that `KeyListener` on which we call `updateUI`. If I type a 20 characters tag name, this `updateUI` is called 20 times. Let's implement a coalescing. have a look at `com.oxygenxml.git.view.CoalescedEventUpdater` and how it is used. Let's take one step further and create a `CoalescingDocumentListener(Runnable)` to simplify the installment of such a support.
> 4. `TagsDialog` - let's not hijack the `Cancel` to delete the tag. What happens now is that when you press ESC it actually deletes the tag instead of closing the dialog. I suggest having something like in the picture below. Actions with icons under the table for `Push` and `Delete` and just a `Close` button under that closes the dialog
>    ![image](https://user-images.githubusercontent.com/7802649/132672382-0d4ff593-1739-4e6b-afb4-22417a521cc1.png)
