### ISSUE TITLE
Git-plugin connection times out

### ISSUE THREAD

**Issue by rekcuz** [oxygenxml/oxygen-git-plugin#68]
Hello,

Thank you for creating this plugin. We are putting it to good use!  

We have an issue where, after a few hours the connection to our git host (bitbucket) times out. The only way to get Oxygen XML to reconnect is a restart of the application.   Is there a way to refresh the plugin connection without having to restart Oxygen?

Thanks!

Joe

**Comment by AlexJitianu** [comment]
Hello,

Unfortunately I didn't manage to reproduce this behavior. It would help if you can give me the full error message. If you start Oxygen from the command line launcher then you might see more information in the console. 
If you are willing to further help us debug this issue, please unzip the attached _log4j.properties_ file ([log4j.zip](https://github.com/oxygenxml/oxygen-git-plugin/files/2449433/log4j.zip))directly in Oxygen's installation directory. Restart Oxygen and reproduce the issue then please send us  the contents of _${user.home}/Desktop/oxygenLog/_ to support@oxygenxml.com.  Afterwards, please delete the log4j.properties file because it can affect the performance with the logging it introduces.



Best regards,
Alex

**Comment by rekcuz** [comment]
Hi Alex,

Mail sent to support@oxygenxml.com with sample log files. Thanks again for looking into this issue.

Joe

**Comment by raducoravu** [comment]
@rekcuz The problem seemed to be caused by the way in which Oxygen XML Editor was reusing HTTP connections. The latest Oxygen version we released (version 21) should no longer have this problem.

**Comment by rekcuz** [comment]
Thank you, @raducoravu!
