### ISSUE TITLE
The prompt to switch on detected repo doesn't always work

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-git-plugin#83]
The prompt to switch on detected repo doesn't always work.

Sometimes, I need to switch between a few projects before it triggers the prompt to switch repos. The workaround is just to use the file chooser, so it's not the end of the world. ;)

**Comment by sorincarbunaru** [comment]
Hi John,

Thank you for the feedback! We will take a look at this and get back to you on this thread once we have any updates on questions about this.

**Comment by sorincarbunaru** [comment]
@kirkilj 

I just checked on my computer, and I couldn't reproduce the issue. I will also ask a colleague of mine to give it a try.

By the way, from what I understand the problem was that the prompt was shown, but confirming the repo switch did not do anything. Is that right? Or was it that the prompt was actually not shown at all?

**Comment by sorincarbunaru** [comment]
Most times it seems to work flawless. The only problem I found is that sometimes, because of the structure of the project, the Git repository is not detected, and the possibility to change the working copy is not presented.

Was this what happened to you too (i.e. the dialog was not shown for specific projects)? Or did it sometimes work for some a project and sometimes didn't?

**Comment by kirkilj** [comment]
Yes, the prompt would not appear at all in those cases. 

If you recall, on a previous issue, I mentioned that on some repos, Oxygen's commit function indicated that a commit was successful, but the stage remains as it was. I have to go to the command line, which confirms that the items that were staged in Oxygen are shown as such with git status. Then I perform the commit there. When I go back into Oxygen, the stage shows as empty correctly. This only happens on some repos however. I'm wondering if it's the same repos that do not trigger the repo prompt when there's a project switch?

All of our repos are on the same Git server.

**Comment by sorincarbunaru** [comment]
Thank you for the info, John! For the next minor version (probably at the end of this month or so) we will fix a bug related to detecting local Git repositories. I hope it will also fix the issue you reported here.

**Comment by AlexJitianu** [comment]
> If you recall, on a previous issue, I mentioned that on some repos, Oxygen's commit function indicated that a commit was successful, but the stage remains as it was. I have to go to the command line, which confirms that the items that were staged in Oxygen are shown as such with git 

In the next release we also fixed what I mentioned on #81 :
https://github.com/oxygenxml/oxygen-git-plugin/issues/81#issuecomment-617814061
I suspect that this is what's happening when the commit appears to be successful, but the view doesn't react and a `git status` also presents the resources as uncommitted.

**Comment by AlexJitianu** [comment]
Release 2.2.0 contains the fix I mentioned above.
